# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ManyToManyField(related_name='Company', to='customers.Company'),
        ),
    ]
