# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20171003_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company',
            new_name='companies',
        ),
    ]
