# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20171003_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
